name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.6.0
        with:
          credentials_json: ${{ secrets.GOOGLE_CLOUD_KEYFILE_JSON }}

      # Step 3: Set up Google Cloud CLI
      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      # Step 4: Authenticate Docker with Google Cloud Artifact Registry
      - name: Authenticate Docker
        run: |
          gcloud auth configure-docker asia-southeast1-docker.pkg.dev

      # Step 5: Create Docker repositories in Artifact Registry
      - name: Create Docker repositories for API and Frontend
        run: |
          gcloud artifacts repositories create dropoff-api \
            --repository-format=Docker \
            --location=asia-southeast1 \
            --description="Docker repository for Dropoff API" || echo "Repository dropoff-api already exists"

          gcloud artifacts repositories create dropoff-calculator-frontend \
            --repository-format=Docker \
            --location=asia-southeast1 \
            --description="Docker repository for Dropoff Frontend" || echo "Repository dropoff-calculator-frontend already exists"

      # Step 6: Build and push API Docker image
      - name: Build and push API Docker image
        run: |
          docker build -t asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/dropoff-api/dropoff-api ./dropoff-api
          docker push asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/dropoff-api/dropoff-api

      # Step 7: Build and push Frontend Docker image
      - name: Build and push Frontend Docker image
        run: |
          docker build -t asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/dropoff-calculator-frontend/dropoff-calculator-frontend ./dropoff-calculator-frontend
          docker push asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/dropoff-calculator-frontend/dropoff-calculator-frontend

      # Step 8: Deploy API to Google Cloud Run
      - name: Deploy API to Google Cloud Run
        run: |
          gcloud run deploy dropoff-api \
            --image asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/dropoff-api/dropoff-api \
            --platform managed \
            --region asia-southeast1 \
            --allow-unauthenticated

      # Step 9: Deploy Frontend to Google Cloud Run
      - name: Deploy Frontend to Google Cloud Run
        run: |
          gcloud run deploy dropoff-calculator-frontend \
            --image asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/dropoff-calculator-frontend/dropoff-calculator-frontend \
            --platform managed \
            --region asia-southeast1 \
            --allow-unauthenticated
