name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.4.0
        with:
          version: "367.0.0" # or the latest version
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Dockerize dropoff-api
        working-directory: ./dropoff-api
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/dropoff-api:${GITHUB_SHA} .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/dropoff-api:${GITHUB_SHA}

      - name: Dockerize dropoff-calculator-frontend
        working-directory: ./dropoff-calculator-frontend
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/dropoff-calculator-frontend:${GITHUB_SHA} .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/dropoff-calculator-frontend:${GITHUB_SHA}

      - name: Deploy dropoff-api to Google Cloud Run
        run: |
          gcloud run deploy dropoff-api \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/dropoff-api:${GITHUB_SHA} \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated

      - name: Deploy dropoff-calculator-frontend to Google Cloud Run
        run: |
          gcloud run deploy dropoff-calculator-frontend \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/dropoff-calculator-frontend:${GITHUB_SHA} \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
